BaseUrl= "https://chihkaiyu.github.io/"
LanguageCode= "zh-TW"
Title= "No Idiots Allowed Here"
paginate = 10
canonifyurls = true
theme = "hyde"
disqusShortname = "chihkaiyu"
hasCJKLanguage = true

[Menus]
  main = [
      {Name = "About", URL = "/page/about"},
      {Name = "Archives", URL = "/post"},
      {Name = "Tags", URL = "/page/tags"},
  ]

[params]
  cover = "images/DSC03509.jpg"
  author = "Chih Kai Yu"
  authorlocation = "Taipei, Taiwan"
  authorwebsite = "https://chihkaiyu.github.io"
  authorbio= "Software Engineer"
  logo = "images/profile.png"
  githubName = "chihkaiyu"
  twitterName = "kai_chihkaiyu"
  googleAnalyticsUserID = "UA-132491233-1"
  hideHUGOSupport = false
  description = "Are you an idiot?"
  
  # Setting a value will load highlight.js and enable syntax highlighting using the style selected.
  # See https://github.com/isagalaev/highlight.js/tree/master/src/styles for available styles
  # A preview of above styles can be viewed at https://highlightjs.org/static/demo/
  hjsStyle = "default"
